### ISSUE TITLE
emotional transfer for target speakers with only neutral data

### ISSUE THREAD

**Issue by leonardoboulitreau** [suhitaghosh10/emo-stargan#17]
Hello! 

First of all, congrats for your awesome work!

I am playing with your demo and trying to convert an emotional source utterance (from ESD) to a target speaker that **only has neutral data** (from VCTK) while preserving the source's emotion, but unfortunately I found the outputs to be always neutral. 

I was wondering if you tried any experiment in this direction, since from the paper, as far as I understood, for a target neutral speaker you only tried with a neutral source utterance (VCTK -> VCTK).

(When the output is from a speaker that has already seen emotional data, the conversion is indeed neat!)

Thanks!

**Comment by suhitaghosh10** [comment]
Thanks for your interest in our work! Yes, since VCTK has no emotional utterances, the speaker-style embeddings for the VCTK speakers dont capture a huge change in pitch or other acoustic properties, which often leads to the observation which you noticed.

**Comment by hhhuazi** [comment]
Hello, thank you very much for sharing the code. I noticed that you have two papers with the same task, and the other one is: StarGAN-VC++: Towards Emotion Preserving Voice Conversion Using Deep Embeddings. But the experimental results are shown in Table 2，The ACC results are different, with some being slightly worse. What is the reason？

**Comment by suhitaghosh10** [comment]
Hey thanks for interest in our work! There starganvc++ paper use only emotion embeddings in the loss, plus there are some other loss functions and minor architectural changes, so the results are also different.
