### ISSUE TITLE
Hello, I would like to inquire about the experimental results.

### ISSUE THREAD

**Issue by hhhuazi** [suhitaghosh10/emo-stargan#18]
Hello, thank you very much for sharing the code. I noticed that you have two papers with the same task, and the other one is: StarGAN-VC++: Towards Emotion Preserving Voice Conversion Using Deep Embeddings. But the experimental results are shown in Table 2，The ACC results are different, with some being slightly worse. What is the reason？

**Comment by suhitaghosh10** [comment]
Hey thanks for interest in our work! There starganvc++ paper use only emotion embeddings in the loss, plus there are some other loss functions and minor architectural changes, so the results are also different.

**Comment by hhhuazi** [comment]
The results in the paper starganvc++ are poor, aren't they？

**Comment by hhhuazi** [comment]
Can this model be used for voice conversion tasks that preserve accents？

**Comment by suhitaghosh10** [comment]
> The results in the paper starganvc++ are poor, aren't they？

we found starganvc++ to preserve emotions better than the baselines and datasets we presented in the paper
