### ISSUE TITLE
Task Conversion

### ISSUE THREAD

**Issue by hhhuazi** [suhitaghosh10/emo-stargan#19]
Can this model be used for voice conversion tasks that preserve accents？

**Comment by suhitaghosh10** [comment]
The speaker embeddings ideally should capture representations of speaker style including accent. In our experiments, we found that if the source and target speakers have the same accent, the accent is preserved. However, if the source and target speakers have different accents, then the converted sample will have the accent of the target speaker, and thats what we also aimed to do (speaker anonymisation).

**Comment by hhhuazi** [comment]
May I ask if you labeled the issue of emotional leakage with an accent or a speaker？
