### ISSUE TITLE
May I ask if you labeled the issue of emotional leakage with accents or speakers？

### ISSUE THREAD

**Issue by hhhuazi** [suhitaghosh10/emo-stargan#20]
Hello, your job is very interesting. Regarding the issue of emotional leakage, may I ask if you labeled the issue of emotional leakage with  accents or  speakers？

**Comment by suhitaghosh10** [comment]
Thanks for your interest. Can you please elaborate your question?

**Comment by hhhuazi** [comment]
I'm sorry I didn't clarify my issue. In your other paper, StarGAN-VC++mentioned in section 2.2: Emission Leakage by Speaker Embedding, using ESD dataset to train the model. I would like to ask if the labels used during training are based on speakers or accounts？
