### ISSUE TITLE
config.yml

### ISSUE THREAD

**Issue by VlaDanilov** [suhitaghosh10/emo-stargan#21]
Dear suhitaghosh10, thank you very much for sharing your research and publish results!
I'm trying to launch the Demo EmoStarGAN Demo.ipynb notes and it seems like config.yml file is missing, could you please provide the config file?
Thank you very much once again

**Comment by suhitaghosh10** [comment]
Hi..thanks for your interest! you can find the config file for training the voice conversion model here: /Configs/speaker_domain_config.yml

**Comment by VlaDanilov** [comment]
Dear suhitaghosh10, thank you for your reply!
Yes, that was my first guess and I tried both, but it seems like there was another config file because non of speaker_domain_config.yml and emotion_domain_config.yml works, each of them return different error messages and both related to the 'num_domains'. 
With speaker_domain_config.yml it's "AttributeError: 'Munch' object has no attribute 'num_domains'". 
With the other it's a bit more complicated, but , as I understand, the problem is that num_domains=5. And in that particular case I don't fully understand how 'num_domains' is related to 'selected_speakers' variable in 'compute_style' function (through the mapping_network class), to me, the issue is there. I don't know if this issue appears for me locally or it's a bug in the code.
I will be very glad if you could clarify it a bit. 
Thank you.

**Comment by suhitaghosh10** [comment]
'selected_speakers' are the speakers for which you want to generate conversions while training. it has no relation to num_speaker_domains. can you please tell me the exact error and the exact place you are getting when you use speaker_domain_config.yml (which is the intended one for voice conversion)

**Comment by VlaDanilov** [comment]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
 1.    emostargan, F0_model, vocoder, reference_embeddings = build_inference_pipeline(device='cpu')
 2.   reference_embeddings = compute_style(emostargan, selected_speakers, speaker_dicts_20)
 3.   ref = starganv2.mapping_network(torch.randn(1, latent_dim).to(device), label)

    [325] s = out[idx, y]  # (batch, style_dim)
    [326] return s

IndexError: index 14 is out of bounds for dimension 1 with size 7
---------------------------------------------------------------------------
I simplified the error log here removing unnecessary links, etc. But the main order showed in numbers 1), 2) and 3). Lines 325 and 326 and in class mapping_network, function 'forward'.

Thank you.

**Comment by suhitaghosh10** [comment]
it looks like you specified 7 speakers but you are trying to index the 14th speaker

**Comment by VlaDanilov** [comment]
> it looks like you specified 7 speakers in your config file but you are trying to index the 14th speaker

Yes, thank you. I hope you will update the appropriate config file to avoid future confusions.

**Comment by suhitaghosh10** [comment]
> > it looks like you specified 7 speakers in your config file but you are trying to index the 14th speaker
> 
> Yes, thank you. I hope you will update the appropriate config file to avoid future confusions.

The config needs to be updated based on your dataset and how many speakers you need. The config file provided works fine with the dataset and the number of target speakers. You always need to update the config files as mentioned in the readme file

**Comment by psvlnandu** [comment]
Hi,
the code is looking for 
FileNotFoundError: [Errno 2] No such file or directory: 'Utils/vocoder/checkpoint-400000steps.pkl' but author has provided the "Utils/vocoder/checkpoint-2500000steps.pkl" right? can you pls confirm this; should i just change the checkpoint name?
