### ISSUE TITLE
Emotion transfer inference

### ISSUE THREAD

**Issue by VlaDanilov** [suhitaghosh10/emo-stargan#23]
Good day, thank you very much for your results!

I have a question concerning the emotion inference, would be nice to have a brief illustration of emotion transfer inference in your Demo code, do you plan to include it as well?

Kind regards,
 V.D.

**Comment by suhitaghosh10** [comment]
since the emotion conversion used in the work has the same architecture and requires the same inference methodology as the voice conversion, we dont plan to include in demo. sorry about that
