### ISSUE TITLE
How well does it generalise for A2M?

### ISSUE THREAD

**Issue by skol101** [suhitaghosh10/emo-stargan#25]
Looking at the results of subjective evaluation there's no SMOS (similarity) results. How well does your model actually genrealise for A2M tasks?

**Comment by suhitaghosh10** [comment]
yes because the objective was anonymisation. although we did not publish similarity between conversion and target speaker, it was as good as the baseline. the improvement was significantly seen in emotion preservation, w.r.t speaker similarity is as good as baseline.
