### ISSUE TITLE
Speaker and Emotional domain training

### ISSUE THREAD

**Issue by skol101** [suhitaghosh10/emo-stargan#27]
You've got 2 config files: speaker domain config for training on VCTK dataset, emotional domain config for training on ESD, yet training instructions mention ONLY speaker domain training.

Would you explain, please?

**Comment by suhitaghosh10** [comment]
The speaker domain config is meant for VC training, nothing to do with vctk. And emotional config file if you want to retrain the emotion conversion network to get the emotion embeddings.

**Comment by skol101** [comment]
It's just that train/val list examples don´t contain any ESD dataset files

**Comment by suhitaghosh10** [comment]
They do contain.pls check again.
