### ISSUE TITLE
GRU and Transformer Encoder Layer 

### ISSUE THREAD

**Issue by VlaDanilov** [suhitaghosh10/emo-stargan#28]
Hello , thank you for your research, very interesting results.
I noticed you have some line of code in the generator part which you actually don't use, but published.
Could you please elaborate a bit on GRU and Encoder methods and how you used them?

**Comment by suhitaghosh10** [comment]
yes, its difficult to accomodate everything in a 4 page paper. so the details can be found in the code. please refer to the code to understand the usage
